#!/usr/bin/env python3
#
# Hook: no-any-type-py
# Event: PreToolUse (Write|Edit)
# Purpose: Block `Any` type hints in Python files.
#
# Python twin of no-any-type.sh (which only covers .ts/.tsx).
#
# WHY PYTHON AND NOT BASH. The TS twin strips comments and string literals before
# matching, because a rule written as `no \`as any\`` inside a message string
# denied its own file. The same trap is worse in Python: `:param x: Any valid
# uuid` in a docstring matches `: Any` exactly, and docstrings are triple-quoted
# strings that no line-oriented sed can see the end of. `tokenize` knows what is
# code and what is not, so the scan runs on NAME/OP tokens only — a comment, a
# docstring or a string literal can say "Any" as often as it likes.
#
# NOTE: on Edit, only the inserted delta (new_string) is inspected, not the whole
#       file. An `Any` already present elsewhere passes through here —
#       backstop = the reviewer agent (correctness dimension).

import io
import json
import os
import re
import sys
import time
import tokenize

# --- timing ------------------------------------------------------------------
# Same log and TSV columns as hook-lib.sh and english-comments.py, so
# hook-timings-report.sh sees this hook too. Off with CWK_HOOK_TIMING=0.
if os.environ.get("CWK_HOOK_TIMING", "1") == "1":
    import atexit

    _T0 = time.time()

    def _record() -> None:
        log = os.path.join(
            os.environ.get("CLAUDE_PROJECT_DIR", os.getcwd()), ".claude", ".hook-timings.log"
        )
        try:
            with open(log, "a") as fh:
                fh.write(
                    "%d\t%s\t%d\t%s\t%s\n"
                    % (_T0 * 1000, "no-any-type-py", (time.time() - _T0) * 1000, "-", "-")
                )
        except OSError:
            pass

    atexit.register(_record)

# Annotation shapes: `: Any`  `-> Any`  `[Any]`  `[Any,`  `, Any]`  `cast(Any`
#
# Every gap is `\s*`, including the one before `(`: `code_only` returns tokens
# joined by spaces, so nothing is adjacent any more and a pattern written against
# the raw source (`cast\(`) silently stops matching.
ANNOTATION_RE = re.compile(
    r":\s*Any\b|->\s*Any\b|\[\s*Any\s*[],]|,\s*Any\s*\]|\bcast\s*\(\s*Any\b"
)

REASON = (
    "Type 'Any' detected. Use a real type instead.\n\n"
    "Alternatives:\n"
    "• object — when you truly accept anything and will narrow it\n"
    "• TypeVar / generic — for a parameterised signature\n"
    "• Protocol — for structural typing of an external client\n"
    "• a Pydantic model or TypedDict — for a JSON payload with a known shape\n"
    "• dict[str, str | int] — an explicit union beats Any"
)


def deny(reason: str) -> None:
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": reason,
        }
    }))
    sys.exit(0)


def code_only(source: str) -> str:
    """The source with comments and string literals blanked out.

    Falls back to the raw source when the delta does not tokenize — an Edit
    inserts a fragment, not a whole module, so that is the common case, not the
    exception. Failing that way keeps the check strict rather than silent; the
    fragment paths that matter (a signature, an annotation) tokenize fine.
    """
    try:
        pieces = []
        for tok in tokenize.generate_tokens(io.StringIO(source).readline):
            if tok.type in (tokenize.COMMENT, tokenize.STRING):
                continue
            # `tok.string` only — never `tok.line`, which would paste the whole
            # original line back in, string literals and comments included, and
            # quietly undo the filter this function exists for.
            pieces.append(tok.string)
        return " ".join(pieces)
    except (tokenize.TokenError, IndentationError, SyntaxError):
        stripped = re.sub(r"#.*$", "", source, flags=re.M)
        stripped = re.sub(r'"""[\s\S]*?"""|\'\'\'[\s\S]*?\'\'\'', "", stripped)
        stripped = re.sub(r'"[^"\n]*"|\'[^\'\n]*\'', "", stripped)
        return stripped


def main() -> None:
    try:
        data = json.loads(sys.stdin.read())
    except Exception:
        sys.exit(0)

    tool_input = data.get("tool_input", {}) or {}
    path = (tool_input.get("file_path") or "").replace("\\", "/")
    content = tool_input.get("content") or tool_input.get("new_string") or ""

    if not path.endswith(".py") or not content:
        sys.exit(0)

    # Migrations are generated by Alembic; its templates use loose typing.
    # Belt and braces: Alembic writes revisions itself, outside Write/Edit, so
    # this hook rarely sees one — it only fires when an agent hand-edits a
    # revision. `migrations/` covers the projects that renamed the directory.
    if re.search(r"/(alembic|migrations)/versions/", path):
        sys.exit(0)

    if ANNOTATION_RE.search(code_only(content)):
        deny(REASON)

    sys.exit(0)


if __name__ == "__main__":
    main()
